apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

images:
- name: merger
  newName: my-registry/chudnovsky-merger
  newTag: latest
- name: worker
  newName: my-registry/chudnovsky-worker
  newTag: latest

resources:
- ../../base

configMapGenerator:
- name: pi-sets-environment-vars
  behavior: replace
  env: pi-sets-demo.env

patches:
- path: pi-worker-statefulset-patch.yaml
  target:
    kind: StatefulSet
    name: pi-worker
- path: pi-worker-vpa-patch.yaml
  target:
    kind: VerticalPodAutoscaler
    name: pi-vpa